UPSTREAM: sched: Export sched_setscheduler_nocheck
The new locktorture rtmutex_lock tests exercise priority boosting, which
means that they need to set some tasks to real-time priority.  To do this,
they use sched_setscheduler_nocheck().  However, this is not exported to
modules, which results in the following error when building locktorture
as a module:

ERROR: "sched_setscheduler_nocheck" [kernel/locking/locktorture.ko] undefined!

This commit therefore adds an EXPORT_SYMBOL_GPL() to allow this function
to be invoked from locktorture when built as a module.

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Davidlohr Bueso <dave@stgolabs.net>
Signed-off-by: Paul E. McKenney <paulmck@linux.vnet.ibm.com>
Acked-by: Ingo Molnar <mingo@kernel.org>
Reviewed-by: Josh Triplett <josh@joshtriplett.org>

Change-Id: I6e07a43188f1e9666479cdc73f97755fdeb2e7a2
[AmitP: Fix undefined "sched_setscheduler_nocheck" error when building
        cpufreq_interactive driver as a module in android-3.18]
(cherry picked from commit 84778472e1b6a27a8931712c40e8cf31143c8f6c)
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>